const DASHBOARD_ACTIONS = {
  SELECT_ISSUE: "SELECT_ISSUE",
  SELECT_ELEMENT: "SELECT_ELEMENT",
  CHANGE_WORKSPACE_MODE: "CHANGE_WORKSPACE_MODE",
  SET_ACTIVE_HIGHLIGHT: "SET_ACTIVE_HIGHLIGHT",
  LOAD_ANALYSIS_RESULT: "LOAD_ANALYSIS_RESULT",
  LOAD_HISTORY_RUN: "LOAD_HISTORY_RUN",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  SET_ACTIVE_PROFILE: "SET_ACTIVE_PROFILE",
  PRINT_REPORT: "PRINT_REPORT",
};

export { DASHBOARD_ACTIONS };

